/**
 * Pelnora H0-3 (f): no-edit round-trip of three synthetic fixtures through the
 * exact path the Pelnora app saves with:
 *
 *   parseDocx → toProseDoc → fromProseDoc → repackDocx
 *
 * Word revisions (w:ins/w:del with author + date), comments, numbering,
 * styles and sectPr columns must be unchanged. The normalized XML diff is
 * limited to the classes listed in `normalize()`: rsid attributes, proofErr
 * markers, attribute order, self-closing form, `xml:space="preserve"` on text
 * that has no leading/trailing whitespace, the `w:bCs`/`w:iCs` complex-
 * script twins the serializer emits next to `w:b`/`w:i`, and `w:tcBorders`
 * the table parser resolves from the table style onto each cell (both are
 * upstream behaviour that predates this work and is visually neutral).
 *
 * Fixtures: e2e/fixtures/pelnora/*.docx — generated by the Pelnora app's
 * scripts/dev/make-test-akta.mjs; every identifier in them is fictional.
 */

import { afterAll, beforeAll, describe, test, expect } from 'bun:test';
import { GlobalRegistrator } from '@happy-dom/global-registrator';
import * as fs from 'fs';
import * as path from 'path';
import JSZip from 'jszip';
import { parseDocx } from '../parser';
import { repackDocx } from '../rezip';
import { toProseDoc } from '../../prosemirror/conversion/toProseDoc';
import { fromProseDoc } from '../../prosemirror/conversion/fromProseDoc';

beforeAll(() => GlobalRegistrator.register());
afterAll(() => GlobalRegistrator.unregister());

const FIXTURES_DIR = path.resolve(__dirname, '../../../../../e2e/fixtures/pelnora');

const FIXTURES = [
  '01_umowa_B2B_uslugi.docx',
  '04_RODO_powierzenie.docx',
  '05_rewizje_i_komentarze.docx',
] as const;

function loadFixture(name: string): ArrayBuffer {
  const buffer = fs.readFileSync(path.join(FIXTURES_DIR, name));
  return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
}

async function partOf(buffer: ArrayBuffer, part: string): Promise<string> {
  const zip = await JSZip.loadAsync(buffer);
  return (await zip.file(part)?.async('text')) ?? '';
}

/** Full app save path, no edits in between. */
async function roundTrip(buffer: ArrayBuffer): Promise<ArrayBuffer> {
  const parsed = await parseDocx(buffer);
  const pm = toProseDoc(parsed);
  const back = fromProseDoc(pm, parsed);
  return repackDocx(back);
}

const count = (xml: string, re: RegExp): number => (xml.match(re) ?? []).length;

/** Normalize the diff classes accepted by H0-3 (f); everything else must match. */
export function normalize(xml: string): string {
  return (
    xml
      .replace(/<\?xml[^>]*\?>\s*/, '')
      .replace(/\s+w:rsid\w*="[^"]*"/g, '')
      .replace(/<w:proofErr[^>]*\/>/g, '')
      .replace(/<w:bCs\/>|<w:iCs\/>/g, '')
      .replace(/<w:tcBorders>[\s\S]*?<\/w:tcBorders>/g, '')
      // xml:space="preserve" only matters when the text has edge whitespace
      .replace(
        /<(w:t|w:delText) xml:space="preserve">([^<]*)<\/\1>/g,
        (_m, tag: string, body: string) =>
          /^\s|\s$/.test(body)
            ? `<${tag} xml:space="preserve">${body}</${tag}>`
            : `<${tag}>${body}</${tag}>`
      )
      // <tag attrs></tag> ≡ <tag attrs/>
      .replace(/<([\w:]+)((?:\s+[\w:]+="[^"]*")*)\s*><\/\1>/g, '<$1$2/>')
      // attribute order
      .replace(
        /<([\w:]+)((?:\s+[\w:]+="[^"]*")+)\s*(\/?)>/g,
        (_m, tag: string, attrs: string, sc: string) => {
          const sorted = attrs
            .trim()
            .split(/\s+(?=[\w:]+=)/)
            .sort()
            .join(' ');
          return `<${tag} ${sorted}${sc}>`;
        }
      )
      .replace(/>\s+</g, '><')
  );
}

const body = (xml: string): string => xml.match(/<w:body>[\s\S]*<\/w:body>/)?.[0] ?? '';

/** Split a body into top-level blocks so a failing diff points at one block. */
function blocks(normalizedBody: string): string[] {
  return (
    normalizedBody.match(
      /<w:p\b[\s\S]*?<\/w:p>|<w:p\b[^>]*\/>|<w:tbl>[\s\S]*?<\/w:tbl>|<w:sectPr>[\s\S]*?<\/w:sectPr>/g
    ) ?? []
  );
}

function expectSameBody(before: string, after: string, label: string): void {
  const nb = normalize(body(before));
  const na = normalize(body(after));
  if (nb === na) return;
  const pb = blocks(nb);
  const pa = blocks(na);
  const diffs: string[] = [];
  for (let i = 0; i < Math.max(pb.length, pa.length) && diffs.length < 3; i++) {
    if (pb[i] !== pa[i]) diffs.push(`block ${i}\n  before: ${pb[i]}\n  after:  ${pa[i]}`);
  }
  throw new Error(`${label}: normalized document.xml differs\n${diffs.join('\n')}`);
}

describe('Pelnora fixtures — no-edit round-trip through the app save path', () => {
  for (const name of FIXTURES) {
    test(`${name}: revisions, comments, cols and structure are unchanged`, async () => {
      const before = loadFixture(name);
      const after = await roundTrip(before);

      const docBefore = await partOf(before, 'word/document.xml');
      const docAfter = await partOf(after, 'word/document.xml');

      for (const [label, re] of [
        ['w:ins', /<w:ins\b/g],
        ['w:del', /<w:del\b/g],
        ['w:delText', /<w:delText\b/g],
        ['w:cols', /<w:cols\b/g],
        ['w:rFonts', /<w:rFonts\b/g],
        ['w:p', /<w:p\b/g],
        ['w:tbl', /<w:tbl>/g],
        ['w:numPr', /<w:numPr>/g],
        ['w:pStyle', /<w:pStyle\b/g],
        ['w:commentRangeStart', /<w:commentRangeStart\b/g],
        ['w:commentReference', /<w:commentReference\b/g],
        ['author Jan Testowy', /w:author="Jan Testowy"/g],
        ['date 2026-08-30', /w:date="2026-08-30T10:15:00Z"/g],
      ] as const) {
        expect(`${label}: ${count(docAfter, re)}`).toBe(`${label}: ${count(docBefore, re)}`);
      }
      expect(docAfter).not.toContain('moveFrom');
      expect(docAfter).not.toContain('moveTo');
      expect(docAfter).toContain('<w:cols w:space="708"/>');

      expectSameBody(docBefore, docAfter, name);

      const commentsBefore = await partOf(before, 'word/comments.xml');
      const commentsAfter = await partOf(after, 'word/comments.xml');
      expect(count(commentsAfter, /<w:comment\b/g)).toBe(count(commentsBefore, /<w:comment\b/g));
      if (commentsBefore) {
        expect(commentsAfter).toContain('w:author="Anna Recenzent"');
        expect(count(commentsAfter, /w:date="2026-08-31T09:00:00Z"/g)).toBe(2);
        expect(commentsAfter).toContain('Sprawdzić, czy kwota jest zgodna z ofertą z 15.08.');
        expect(commentsAfter).toContain(
          'Proponuję trzykrotność — standard rynkowy dla lokali biurowych.'
        );
      }

      // Untouched parts stay byte-identical.
      for (const part of ['word/styles.xml', 'word/settings.xml', 'word/numbering.xml']) {
        expect(await partOf(after, part)).toBe(await partOf(before, part));
      }
    });
  }

  test('05: the Word revisions keep their ids and wrap the same text', async () => {
    const after = await roundTrip(loadFixture('05_rewizje_i_komentarze.docx'));
    const xml = await partOf(after, 'word/document.xml');
    expect(xml).toContain(
      '<w:del w:id="1" w:author="Jan Testowy" w:date="2026-08-30T10:15:00Z"><w:r><w:delText>120 m²</w:delText></w:r></w:del>'
    );
    expect(xml).toContain(
      '<w:ins w:id="2" w:author="Jan Testowy" w:date="2026-08-30T10:15:00Z"><w:r><w:t>135 m²</w:t></w:r></w:ins>'
    );
    expect(xml).toContain('<w:del w:id="4" w:author="Jan Testowy"');
    expect(xml).toContain('<w:ins w:id="5" w:author="Jan Testowy"');
    expect(xml).toContain('<w:commentRangeStart w:id="100"/>');
    expect(xml).toContain('<w:commentRangeEnd w:id="101"/>');
  });
});
